kind: pipeline
type: docker
name: build-and-test

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  - name: setup
    image: golang:1.26.2-alpine
    commands:
      - apk add --no-cache git make
      - go mod download

  - name: lint
    image: golang:1.26.2-alpine
    commands:
      - go fmt ./...
      - go vet ./...

  - name: test
    image: golang:1.26.2-alpine
    commands:
      - go test -v -race -coverpkg=./... ./...

  - name: build
    image: golang:1.26.2-alpine
    commands:
      - make build
    when:
      event:
        - push
        - pull_request

---
kind: pipeline
type: docker
name: release

trigger:
  ref:
    - refs/tags/v*

steps:
  - name: build
    image: golang:1.26.2-alpine
    commands:
      - apk add --no-cache make
      - make build

  - name: release
    image: node:lts
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_PAT
      GITHUB_EMAIL:
        from_secret: GITHUB_EMAIL
      GITHUB_NAME:
        from_secret: GITHUB_NAME
    commands:
      - export PATH="$HOME/.bun/bin:$PATH"
      - git config --global user.email "$GITHUB_EMAIL"
      - git config --global user.name "$GITHUB_NAME"      
      - node install
      - npx semantic-release
