kind: pipeline
type: docker
name: build-and-test

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  - name: setup
    image: golang:1.26.2-alpine
    commands:
      - apk add --no-cache git make
      - go mod download

  - name: lint
    image: golang:1.26.2-alpine
    commands:
      - go fmt ./...
      - go vet ./...

  - name: test
    image: golang:1.26.2-alpine
    commands:
      - go test -v -cover ./...

  - name: build
    image: golang:1.26.2-alpine
    commands:
      - apk add --no-cache make
      - make build
    when:
      event:
        - push
        - pull_request

---
kind: pipeline
type: docker
name: release

trigger:
  ref:
    - refs/tags/v*

steps:
  - name: build
    image: golang:1.26.2-alpine
    commands:
      - apk add --no-cache make
      - make build

  - name: publish-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_PAT
      files:
        - bin/*
      checksum: sha256
    when:
      ref:
        - refs/tags/v*

---
kind: pipeline
type: ssh
name: deploy

server:
  host: 
    from_secret: MCP_SERVER_HOST
  user: 
    from_secret: MCP_SSH_USER
  password:
    from_secret: MCP_SSH_PASSWORD

steps:
  - name: deploy
    environment:
    commands:
      - make build
      - go --version
      - CURRENT_PATH=$(pwd)
      - echo "CURRENT_PATH=$CURRENT_PATH"
      - /opt/mcpbridge-go/mcpbridgego --stop
      - cp ./bin/mcpbridgego /opt/mcpbridge-go
      - cd /opt/mcpbridge-go
      - ./mcpbridgego --start
       